# Server Properties
server:
    port: 8080

# Development Tool Flags
spring:
    datasource: 
        url: jdbc:mysql://121.134.238.182:3306/auth?serverTimezone=UTC
        driverClassName: com.mysql.jdbc.Driver
        username: authdev
        password: 1qaz!QAZ
    jpa:
        hibernate:
            ddl-auto: none
        database: mysql
        
# OAuth Client Authentication Information
jwt:
    clientId: test-client
    client-secret: secret
    accessTokenValidititySeconds: 43200     # 12 hours
    authorizedGrantTypes: password,authorization_code,refresh_token
    refreshTokenValiditySeconds: 2592000    # 30 days

# Log Levels
logging:
    level:
        org:
            hibernate:
                SQL: DEBUG